apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-prod
  labels:
    app: web-Deploy
    namespace: web1
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web-Deploy 
      app: nginx   
  template:
    metadata:
      name: web-prod
      labels:
        app: web-Deploy 
        app: nginx 
    spec:              
      containers:
        - name: web
          image: nginx:1.11.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "400Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
